### ISSUE TITLE
Tags have disappeared

### ISSUE THREAD

**Issue by rmccue** [stuttter/ludicrousdb#101]
The 4.0.0 and 4.2.0 tags have disappeared from the repo. This has caused them to also disappear [from Packagist](https://packagist.org/packages/stuttter/ludicrousdb), which means we're no longer able to install packages 🙃 

They should be:
* `4.0.0`: 68be1c40fccbdbcc79c5665022c46ff980e958cc
* `4.2.0`: d5d27fc4e19ccfeecac627130e1ec68a800ca381

I'm not sure how this happened?

**Comment by rmccue** [comment]
This was fixed, thanks to @spacedmonkey and @JJJ. :)

**Comment by JJJ** [comment]
Sorry again for whatever the’heck happened!
