### ISSUE TITLE
check_tcp_responsiveness causes [Warning] Aborted connection to db: 'unconnected' user: 'unauthenticated' (This connection closed normally without authentication) after MariaDB 10.4 upgrade

### ISSUE THREAD

**Issue by archon810** [stuttter/ludicrousdb#102]
Hi,

MariaDB 10.4 produces a ton of these warnings

```
[Warning] Aborted connection 46 to db: 'unconnected' user: 'unauthenticated' host: 'XXXXXXXX' (This connection closed normally without authentication)
[Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host: 'XXXXXXXX' (This connection closed normally without authentication)
[Warning] Aborted connection 51 to db: 'unconnected' user: 'unauthenticated' host: 'XXXXXXXX' (This connection closed normally without authentication)
...
```

which were not present in 10.3 or 10.2, which I traced down to check_tcp_responsiveness being set to true and this line of code:

https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L1797

We've had check_tcp_responsiveness enabled for years, and it sounds like a useful feature, so I'm kind of unsure what to do. But leaving the db logs flooded with these messages is not great either.

Any ideas on fixing or adapting to this behavior?

**Comment by archon810** [comment]
Any updates on this? Setting `check_tcp_responsiveness` to false fixes this flood, but I'm not sure if there are any negative side effects for when a host does go down (times out or refuses connection) vs having it enabled.

**Comment by JJJ** [comment]
Hi @archon810, thanks for reporting this, and sorry for the silence here.

Checking TCP responsiveness is, like you said, pretty useful to do. Generally, you should not need to disable it.

Strange that this is different between MariaDB versions for you. I haven't seen this yet myself. I'm up to:

```
Ver 15.1 Distrib 10.5.6-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

Do you know if you're using a persistent object cache? If not, then it's plausible that it isn't timing out correctly.

I also found these:
https://jira.mariadb.org/browse/MDEV-19469
https://mariadb.com/kb/en/cannot-connect-to-10411-from-localhost-windows/
...so it is also plausible it was a MariaDB bug, or related to MariaDB config.

**Comment by JJJ** [comment]
I've identified some improvements to the TCP responsiveness code, and put them together into a pull request for others to try. (I'm running it myself now, in production, over at https://jjj.blog.)

Keeping an eye on it!

**Comment by archon810** [comment]
Any further updates @JJJ @spacedmonkey?

**Comment by JJJ** [comment]
None from me, but I'm not seeing the errors that you are.

Were you able to try the linked PR, @archon810?

**Comment by archon810** [comment]
I have not, we've been on 4.1 waiting to upgrade to 5.1 (and now I'm also seeing 4.2?).

**Comment by JJJ** [comment]
There were some issues with the 4.2.0 tag (my fault) that have been resolved. You may want to give it a try first. It is the latest stable version of the 4.x branch.

**Comment by archon810** [comment]
Should I not aim to upgrade to the 5.X branch instead, at least when the fixes in this ticket and whatever else is pending are fixed?

**Comment by JJJ** [comment]
Oh, definitely. But there was a 5.0.0 release already, and you aren't using it yet, so I assumed you were on 4.x for some reason (I know some folks are.)

**Comment by archon810** [comment]
Oh yeah, we're still on 4.1, as I mentioned above. I think we were waiting for 5.1 before upgrading to 5.X but I don't recall exactly all the reasons why anymore.

Perhaps it was this ticket (#102) as well as #94 and whatever it's referencing.

**Comment by subhamrenu** [comment]
once try with mysqladmin flush-hosts, Maybe due exceed of connections blocked from a particular host.
