### ISSUE TITLE
Tag 4.2  has a ludicrousdb.php file that says "Version: 5.0.0"

### ISSUE THREAD

**Issue by cordulack** [stuttter/ludicrousdb#121]
We are looking to upgrade to the latest version of ludicrousdb and I was hoping someone could clarify something.

When you look at the code in the [4.2 tag](https://github.com/stuttter/ludicrousdb/releases/tag/4.2.0), `ludicrousdb.php` says it is version 5.0. Should the tag and the version in this file match? 

https://github.com/stuttter/ludicrousdb/blob/4.2.0/ludicrousdb.php#L11

```
/**
 * Plugin Name: LudicrousDB
 * Plugin URI:  https://github.com/stuttter/ludicrousdb
 * Author:      JJJ & Friends
 * Author URI:  https://github.com/stuttter/ludicrousdb/graphs/contributors
 * License:     GPL v2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: ludicrousdb
 * Version:     5.0.0
 * Description: An advanced database interface for WordPress that supports replication, fail-over, load balancing, and partitioning
 */
```

Thanks!

**Comment by JJJ** [comment]
That's really annoying. I think this is because the 4.2 tag was being deleted by the mirror, and we had to force the tag, and it just got missed.

It's embarrassing, but won't break anything. When we release 5.1.0, it'll still be OK.

**Comment by leonstafford** [comment]
@JJJ is it not also related to the emojified release name or the date on 4.2.0 GH release being newer than 5.0.0?

<img width="984" alt="LudicrousDB releases page" src="https://user-images.githubusercontent.com/2066833/128618777-1f13f6d1-b719-4411-a875-6db8cb92cb62.png">

<img width="341" alt="LudicrousDB GitHub sidebar" src="https://user-images.githubusercontent.com/2066833/128618788-2d1309b4-81a1-442c-8a59-1884b25507c1.png">

I think you can fix the emojis/force update the 5.0.0 tag/release date to have it shown as latest, without any ill effects ([Packagist](https://packagist.org/packages/stuttter/ludicrousdb) shows 5.0.0 as latest correctly already)

**Comment by leonstafford** [comment]
If someone's trying to check what version is installed on a non-Composerified site, can compare the 5.0.0 and 4.2.0 tags here: https://github.com/stuttter/ludicrousdb/compare/5.0.0...4.2.0

and easy check is the `./ludicrousdb.php` file, line 44, should have the `// phpcs:ignore` comment, as per current master branch: https://github.com/stuttter/ludicrousdb/blob/dc3167b9696e9adbb3834a39453c2cc5575c65c4/ludicrousdb.php#L44

**Comment by thefrosty** [comment]
So really 4.2.0 is newer in features over 5.0.0?

**Comment by JJJ** [comment]
> So really 4.2.0 is newer in features over 5.0.0?

No. 5.0.0 is newer. 5.1.0 is latest.

The 4.2.0 tag was pushed in error by a mirror I'd setup an was half broken. 😔

**Comment by JJJ** [comment]
Closing this. Automatic mirroring is disabled.
