### ISSUE TITLE
Remove deprecated mysql_

### ISSUE THREAD

**Issue by kkmuffme** [stuttter/ludicrousdb#124]
As of PHP 7+ mysql_ isn't supported anymore. Years have passed since PHP7 was released and WP core also recommends PHP 7+ (the legacy support for PHP <7 will be dropped soon)

We should remove the mysql_ things and only keep mysqli_, as it's about time.

**Comment by JJJ** [comment]
Milestoned for 6.0, where we can announce dropping this and making PHP7 a hard cut.

**Comment by spacedmonkey** [comment]
@JJJ Now that PHP 7 in the min for core. We should think about this ticket again.,

**Comment by rfair404** [comment]
@JJJ I wonder if this can be completed as it seems like #150  and #153 have addressed the concerns.

**Comment by JJJ** [comment]
> @JJJ I wonder if this can be completed as it seems like #150 and #153 have addressed the concerns.

Should be able to, yes. Don't suppose you have (or could) test and/or give the code changes a once-over? 🥇
