### ISSUE TITLE
Fatal error in combination with WP Redis and TCP Responsiveness Check

### ISSUE THREAD

**Issue by ouun** [stuttter/ludicrousdb#126]
Hi @JJJ,
first of all thank you so much for LudicousDB. I am currently taking the first steps and I am facing an issue that has been mentioned already before: https://github.com/stuttter/ludicrousdb/pull/67#issuecomment-458830179

Using WP Redis by Pantheon for Object Cache I also receive `Fatal error: Uncaught Error: Call to a member function add_global_groups() on null in .../object-cache.php:245`. Already tried different versions of LudicrousDB such as 4.1, 4.2, 5.0, dev-master & issue/102 but can't find or solve the error. It only comes up with `check_tcp_responsiveness` set to `true`. 

I followed the logics in `class-ludicrousdb.php` from `tcp_cache_get()` -> `tcp_is_cache_persistent()` -> `add_global_group()` up to `wp_cache_add_global_groups()` in `object-cache.php`. Here the global `$wp_object_cache` is null when called and therefore the error happens.

And now I am lost as I don't understand how it comes that the global `$wp_object_cache` is null. Is it a runtime issue, an issue with LudicousDB or with WP Redis?

Would be great if you could have a look and let me know if this is solvable. Also found an closed issue in the WP Redis repo and commented there, too: https://github.com/pantheon-systems/wp-redis/issues/234#issuecomment-879355005

Thank you so much and kind regards!

**Comment by dudenk** [comment]
in my case, change public $check_tcp_responsiveness = false;

**Comment by rfair404** [comment]
@JJJ - I am tracking this release, as the php 8.1+ compatibility is something that I hope to include in an upcoming release of a site that uses ludicrousdb. That said, this issue, is included as part of the milestone, but appears to be related to a third party plugin / platform. I am curious if it indeed needs to be addressed for the 5.1.0 milestone to be completed, or if it can be removed.

**Comment by JJJ** [comment]
@rfair404 fine to move to 6.0.0.

This does still need to be addressed. 👍
