### ISSUE TITLE
PHP 8.1 | wpdb::_real_escape(): fix "passing null to non-nullable" deprecation notices

### ISSUE THREAD

**Issue by spacedmonkey** [stuttter/ludicrousdb#128]
https://github.com/WordPress/wordpress-develop/pull/1628

**Comment by archon810** [comment]
Any updates here please?

**Comment by JJJ** [comment]
Fixed via 80a144a8d8787a86cd95b46a2b9b48fdba76d76f.

Apologies for not seeing this issue then 🫶
