### ISSUE TITLE
need help in configuring 

### ISSUE THREAD

**Issue by deepak166** [stuttter/ludicrousdb#129]
I want to split the database of multisite  into 100 dbs, db00, db01, so on upto db99 .and when a new blog gets added to the multisite, the last two digits of the blog id go to a specified database,
for example,
We can predict what database a blog is in by looking

at the last two digits of the id. Examples:
blog_id: 9, in db09
blog_id: 74, in db74
blog_id: 999989, in db89
blog_id: 9200, in db00
I almost set up everything as in the instruction but don't know how to configure this algorithm
when i try to do , i keep getting critical error

**Comment by JJJ** [comment]
Moved to: https://github.com/stuttter/ludicrousdb/discussions/156
