### ISSUE TITLE
Locking functions are incorrectly marked as read-only

### ISSUE THREAD

**Issue by rmccue** [stuttter/ludicrousdb#133]
In `::is_write_query`, SELECTs are treated as non-write queries:

https://github.com/stuttter/ludicrousdb/blob/dc3167b9696e9adbb3834a39453c2cc5575c65c4/ludicrousdb/includes/class-ludicrousdb.php#L403-L415

However (as we've just found out) there are some functions which can be called within MySQL under SELECT which act as writes; namely, [locking functions](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html).

These functions perform writes, and hence fail with an error if executed on reader DBs.

e.g. try `SELECT GET_LOCK( 'test', 60 )` and you'll see it fail with a read-only error on the reader instance.

(Ref https://github.com/humanmade/altis-cloud/issues/547)

**Comment by JJJ** [comment]
I sloppily merged this via: https://github.com/stuttter/ludicrousdb/commit/ef17c79f65161ad63034184454e5863260be492c

Apologies for the mess. I did not see/remember this issue before cleaning up that PR.

Thank you, as always, for everything 💗
