### ISSUE TITLE
Drop the need for wp_parse_args to avoid the dependency

### ISSUE THREAD

**Issue by shadyvb** [stuttter/ludicrousdb#134]
Using wp_parse_args in https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L343 adds an unnecessary dependency on `wp-includes/functions.php` which limits the ways the drop-in can be loaded.

Replacing `wp_parse_args` with `array_merge` would have the same behavior.

**Comment by JJJ** [comment]
See: https://github.com/stuttter/ludicrousdb/commit/8217a62387c38329f6f7e9f7eeaee9afeb263c8c

**Comment by JJJ** [comment]
Also: https://github.com/stuttter/ludicrousdb/commit/547e91a79e0609434a6e80dd8d03697a6db30267
