### ISSUE TITLE
Doesn't support Composer 2

### ISSUE THREAD

**Issue by SteelWagstaff** [stuttter/ludicrousdb#135]
LudicrousDB doesn't support Composer 2: https://github.com/stuttter/ludicrousdb/blob/dc3167b9696e9adbb3834a39453c2cc5575c65c4/composer.json#L23 
We'd like to update our bedrocks to using Composer 2, but can't when they include ludicrousdb as a dependency. Would you consider updating dependency to something like: `"composer/installers": 1 - 2` or `"composer/installers": "~1.0 || ~2.0"`?  PR address this exists as #136

**Comment by JJJ** [comment]
Merged!
