### ISSUE TITLE
Potential Regex issue failing to redirect INSERT ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by wiglesworthj** [stuttter/ludicrousdb#137]
Hi all!

Firstly, thank you for developing this amazing plugin. It is critical to our deployed WordPress infrastructure, WordPress Docker containers distributed between two servers on a remote island (primary) and cloud servers in California (failover). Our databases are setup in a cyclical master (island)  -> master (island) -> master (cloud) configuration. For the most part, we do not utilize our cloud redundancies, except in the case of local failure. 

Sometime last year, our databases began de-syncing anytime traffic was routed to our cloud failover and the local databases were online. The cloud server was accurately reading from the nearby cloud database, but it was also sending a couple of writes to it as well (previously, it would only send writes to the cloud database if the local instances are offline).

We temporarily solved this issue by putting two of our master databases in read only mode, however this makes failing over to the cloud a manual process. Error messages included below:

`` PHP message: WordPress database error The MySQL server is running with the --read-only option so it cannot execute this statement for query INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_transient_doing_cron', '1652746899.2439739704132080078125', 'yes') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`) made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, _wp_cron, spawn_cron, set_transient, add_option" ``

Appreciate any advice or thoughts. Thank you!

**Comment by JJJ** [comment]
Tangentially related: https://github.com/Automattic/HyperDB/pull/112/commits/6a2ff3bd3428372044e749b3a33f3cc5cb32b12a

**Comment by JJJ** [comment]
It is _possible_ that 10ab45c could fix this, but... I think, I doubt it. 😅

Are you able to replicate this still? If so, are you comfortable testing with the latest master branch to see if it's better?

**Comment by JJJ** [comment]
5.2.0 is out with some improvements related to this.

Hopefully fixed!
