### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by pentatonicfunk** [stuttter/ludicrousdb#144]
Reference : https://make.wordpress.org/core/2022/01/10/wordpress-5-9-and-php-8-0-8-1/#php-8-1-mysqli-default-error-mode-changed

wpdb now implement:
```
/*
			 * Set the MySQLi error reporting off because WordPress handles its own.
			 * This is due to the default value change from `MYSQLI_REPORT_OFF`
			 * to `MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT` in PHP 8.1.
			 */
			mysqli_report( MYSQLI_REPORT_OFF );
			```
			ludicrousdb should implement the same

**Comment by JJJ** [comment]
Thank you @ocean90 for the ping. Appreciate ya!
