### ISSUE TITLE
Notice errors

### ISSUE THREAD

**Issue by spacedmonkey** [stuttter/ludicrousdb#15]
Getting the following notice errors. 

<b>Notice</b>:  Undefined variable: write in <b>/var/www/wp-content/dropins/ludicrousdb/db.php</b> on line <b>675</b><br />
<b>Notice</b>:  Undefined variable: write in <b>/var/www/wp-content/dropins/ludicrousdb/db.php</b> on line <b>703</b><br />

**Comment by johnjamesjacoby** [comment]
Fixed in ef886f265a2a55eb2c1de527d6c72823f9aa2fb3.
