### ISSUE TITLE
PHP 8.2 deprecated methods.

### ISSUE THREAD

**Issue by rfair404** [stuttter/ludicrousdb#150]
When running in php 8.2, I am getting several of the following messages: 

```
Deprecated: mysqli_get_client_info(): Passing connection object as an argument is deprecated in .../wp-content/mu-plugins/ludicrousdb/ludicrousdb/includes/class-ludicrousdb.php on line 1601
```

It seems like this plugin is over due for a php 8.x update.

**Comment by rfair404** [comment]
@JJJ thank you for giving this some attention. It is possible that this [commit](https://github.com/stuttter/ludicrousdb/commit/39ef0ee7f7c3d17ffd4735e48ed831b870d2a33c) addresses these concerns.

**Comment by JJJ** [comment]
@rfair404 Agree that your issue should be resolved now.

Additionally, #124 will remove support for the old stuff permanently.

Thank you for your patience!
