### ISSUE TITLE
Lack of tags/releases

### ISSUE THREAD

**Issue by romulodl** [stuttter/ludicrousdb#18]
Could you please tag/release versions when a new change/feature come in?

Thanks :)

**Comment by spacedmonkey** [comment]
Thanks for your feedback @romulodl . I am working on ludicrousdb today and I will see what I can do. There will be a number of changes coming in the next couple of days, keep on eye on this repo.

**Comment by schrapel** [comment]
Can you at least put a tag on https://github.com/stuttter/ludicrousdb/commit/6f183ea82c220d21f93bec384d6faf9106ba4754

We currently have dev-master in our Composer

**Comment by johnjamesjacoby** [comment]
Tagged 2.1.0.

We'll be sure to tag going forward.
