### ISSUE TITLE
Question about implementation

### ISSUE THREAD

**Issue by dereckmartin** [stuttter/ludicrousdb#19]
This works well for what I am trying to accomplish with it.  However, it would be optimal if this wasn't in the plugins directory.  I do not want clients I will be hosting to even see this in their list of plugins.  The best I can do with out altering the code is place read-only permissions, so it can't be deleted. 

Is there a simple solution for this to be installed and used, that doesn't require it to be installed as a plugin?

**Comment by gonssal** [comment]
Place in `wp-content/mu-plugins`.

**Comment by JJJ** [comment]
> Place in wp-content/mu-plugins.

Bingo. Closing this, but please feel free to reply & continue a dialogue here for more help.
