### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by schrapel** [stuttter/ludicrousdb#20]
This goes back all the way to HyperDB, so I know it wasn't you but are you able to explain these lines?

$this->dataset is never used and $dataset can never be empty :/

https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L353-L361

**Comment by JJJ** [comment]
Hey Toby. Good question.

This is part of the `db_connect()` method, and is taken both from HyperDB and WordPress's original `WPDB` class. The first part of this method tries to assess what dataset to use, depending on what's been passed through or defined in a callback somewhere else using `run_callbacks( 'dataset' )`.

You're correct that `$this->dataset` isn't used directly. All this bit of code does is stash the `$dataset` variable so it's available any other time.

From the docs:

> A dataset is defined as a group of tables that are located in the same database. There may be similarly-named databases containing different tables on different servers. There may also be many replicas of a database on different servers. The term "dataset" removes any ambiguity. Consider a dataset as a group of tables that can be mirrored on many servers.

An empty dataset condition could happen, and if it does, it's important for the database class to compensate for that erroneous state. The most common time this happens is if a plugin creates a custom database table that you haven't defined or added in your configuration.

Say you activate BuddyPress, but there is no callback or definition of it's extra tables. If `$this->callback_result` exists as an array of defined database tables & locations, and the `dataset` defined in the callback is an empty value, the `extract()` function may put out an empty dataset, but one that is-set.

This also confirms a bit why I don't like `isset()` in general usage. We should be setting smart defaults ahead of time to provide a more predictable environment for developers to work inside of, so you're correct to note that this bit of code is... less clean that I would prefer it to be.

It mostly comes down to the `add_database()` method, where this happens:

```
		$dataset = isset( $db['dataset'] )
			? $db['dataset']
			: 'global';
```

That `isset()` could be an `empty()` check, to prevent empty datasets ahead of time. Then that later check could get cleaned up to prevent an `isset()` check also.

Hopefully this helps a little bit. Thanks for pointing this out.
