### ISSUE TITLE
Multisite blog tables in db-config

### ISSUE THREAD

**Issue by thegronix** [stuttter/ludicrousdb#22]
Hello! There is in db-config.php:

`// Multisite blog tables are "{$base_prefix}{$blog_id}_*"
function my_db_callback( $query, $wpdb ) {
    if ( preg_match("/^{$wpdb->base_prefix}\d+_/i", $wpdb->table) ) {
        return 'blog';
    }
}`

So, this fragment for WPMU must look like this?

`function my_db_callback( $query, $wpdb ) {
    if ( preg_match("/^{$base_prefix}{$blog_id}_\d+_/i", $wpdb->table) ) {
        return 'blog';
    }
}`

**Comment by JJJ** [comment]
The callback, and the regular expression inside of it, is mostly up to you and your approach to naming your database tables. The example you've included is a pretty vanilla guide for a largely unchanged WordPress installation.

It's basically telling LudicrousDB that anytime a database table matches a base prefix & blog ID, make sure it targets the `blog` server for them.
