### ISSUE TITLE
Tcp_cache functions

### ISSUE THREAD

**Issue by spacedmonkey** [stuttter/ludicrousdb#27]
The tcp cache functions set / get were converted to use wp_cache_ api. On the face of it, this is a good idea. However, database drop-ins are loaded before object-cache drop-in. This means that possibly have an a race condition where wp_cache_ is called before it exists.

**Comment by JJJ** [comment]
If `advanced-cache.php` is in use, traditionally it will kick-start the object cache with a call to `wp_start_object_cache()`.

If that's not the case, `wp_start_object_cache()` is called almost immediately after `require_wp_db()` in `wp-settings.php`, so while the load order is tight, it's unlikely to cause any issues.
