### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by GeneralCan** [stuttter/ludicrousdb#34]
Is php7 support something you're looking into for a future build?

**Comment by spacedmonkey** [comment]
This is actively maintained project. As I understand it works in PHP 7.0. Are you moving issues this it the plugin in PHP 7.0?

**Comment by GeneralCan** [comment]
was getting some _mysql errors. but it was my fault. sorry about that.

**Comment by JJJ** [comment]
Phew.

It's paramount that LDB work with all modern PHP versions (at least 7.0 and 7.1 as of today.)

**Comment by spacedmonkey** [comment]
For what is worth, I am using LDB in production using PHP 7.0. Works a treat
