### ISSUE TITLE
how to know if it is working

### ISSUE THREAD

**Issue by stephenlane** [stuttter/ludicrousdb#36]
Hi there,

I have attempted to implement master slave and have no idea if it is working. Any help would be much appreciated.

Regards,

Stephen

**Comment by takotakot** [comment]
ref: #35 
For example, please try to change the password for master server. That will be the test for connecting to slave server.
There are many other ways to test.

**Comment by JJJ** [comment]
I've considered building in some kind of UI, or support for the Query Monitor plugin from @johnbillion. Maybe we can do some fancy collaboration work to help you with this eventually.

**Comment by stephenlane** [comment]
so my issue is I have set up my master slave on aws and have added the following config in the db-config.php file but dont I am not getting any activity on my read database

```
$wpdb->add_database( array(
'host'     => '********.eu-west-1.rds.amazonaws.com',     // If port is other than 3306, use 
'user'     => '*****',
	'password' => '*****',
	'name'     => '*****',
	'write' => 1,
	'read'  => 0,
) );

/**
 * This adds the same server again, only this time it is configured as a slave.
 * The last three parameters are set to the defaults but are shown for clarity.
 */
$wpdb->add_database( array(
	'host'     => '********.eu-west-1.rds.amazonaws.com',     // If port is other than 3306, use host:port.
	'user'     => '*****',
	'password' => '*****',
	'name'     => '*****',
	'write'    => 0,
	'read'     => 1
) );
```

**Comment by takotakot** [comment]
@stephenlane Can you set `'write'    => 0` for master server for testing? I think it's important for problem isolation.

**Comment by JJJ** [comment]
It could be that `$use_master` is kicking in. The `dbhname` will have `__r` in it for read, `__w` for write. This happens in the `db_connect()` method.

It could a custom callback routing it via `$wpdb->add_callback()`, or database tables that were added to the master database definition, but not the slave.

Are your comfortable posting your complete config somewhere (omitting the obvious for security sake.)

**Comment by stephenlane** [comment]
@takotakot  I have set write to 0 and read to 0 and the default db connection in wp-config is the run that runs

**Comment by stephenlane** [comment]
@JJJ what I have done is placed db-config in the same location as wp-config. Then in the wp-content directory I have added the db.php file and then installed the plugin like any other plugin.

My full dp-config file is as follows:
`

<?php

/**
 * LudicrousDB configuration file
 *
 * This file should be copied to ABSPATH/db-config.php and modified to suit your
 * database environment. This file comes with a basic configuration by default.
 *
 * See README.md for documentation.
 */

// Exit if accessed directly
defined( 'ABSPATH' ) || exit;

/**
 * charset (string)
 * This sets the default character set. Since WordPress 4.2, the suggested
 * setting is "utf8mb4". We strongly recommend not downgrading to utf8,
 * using latin1, or sticking to the default: utf8mb4.
 *
 * Default: utf8mb4
 */
$wpdb->charset = 'utf8mb4';

/**
 * collate (string)
 * This sets the default column collation. For best results, investigate which
 * collation is recommended for your specific character set.
 *
 * Default: utf8mb4_unicode_ci
 */
$wpdb->collate = 'utf8mb4_unicode_ci';

/**
 * save_queries (bool)
 * This is useful for debugging. Queries are saved in $wpdb->queries. It is not
 * a constant because you might want to use it momentarily.
 * Default: false
 */
$wpdb->save_queries = false;

/**
 * persistent (bool)
 * This determines whether to use mysql_connect or mysql_pconnect. The effects
 * of this setting may vary and should be carefully tested.
 * Default: false
 */
$wpdb->persistent = false;

/**
 * max_connections (int)
 * This is the number of mysql connections to keep open. Increase if you expect
 * to reuse a lot of connections to different servers. This is ignored if you
 * enable persistent connections.
 * Default: 10
 */
$wpdb->max_connections = 10;

/**
 * check_tcp_responsiveness
 * Enables checking TCP responsiveness by fsockopen prior to mysql_connect or
 * mysql_pconnect. This was added because PHP's mysql functions do not provide
 * a variable timeout setting. Disabling it may improve average performance by
 * a very tiny margin but lose protection against connections failing slowly.
 * Default: true
 */
$wpdb->check_tcp_responsiveness = true;

/**
 * This is the most basic way to add a server to LudicrousDB using only the
 * required parameters: host, user, password, name.
 * This adds the DB defined in wp-config.php as a read/write server for
 * the 'global' dataset. (Every table is in 'global' by default.)
 */
$wpdb->add_database( array(
	'host'     => '***.eu-west-1.rds.amazonaws.com',     // If port is other than 3306, use host:port.
	'user'     => '***',
	'password' => '***',
	'name'     => '***',
	'write' => 1,
	'read'  => 0,
) );

/**
 * This adds the same server again, only this time it is configured as a slave.
 * The last three parameters are set to the defaults but are shown for clarity.
 */
$wpdb->add_database( array(
	'host'     => '***.eu-west-1.rds.amazonaws.com',     // If port is other than 3306, use host:port.
	'user'     => '***',
	'password' => '***',
	'name'     => '***',
	'write'    => 1,
	'read'     => 1,
	'dataset'  => 'global',
	'timeout'  => 0.2,
) );


`

**Comment by takotakot** [comment]
@stephenlane 

>  is the run that runs

I think db-config.php is not load or ludicrousdb is not working correctly.  
As far as I know, DB setting in wp-config.php can be removed if we configured ludicrousdb correctly. So,

* Try to comment out DB setting in wp-config.php (db-config.php is really used?)
* Write `exit('error');` at the top of db-config.php (db-config.php is load?)

may help you.

If some error is introduced, it is 'configuration' problem. If not, try to set up ludicrousdb again.

**Comment by stephenlane** [comment]
I have tried the above and no luck :(

**Comment by stephenlane** [comment]
in log file getting this error.

`PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/mall/wp-includes/wp-db.php on line 1538" while reading response header from upstream, client: *****, server: _, request: "POST /mall/wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "****", referrer: "http://********/mall/wp-admin/plugins.php?plugin_status=all&paged=1&s"`


Any help much appreciated

**Comment by takotakot** [comment]
@stephenlane What do you mean by "no luck"? Set up ludicrousdb again!

**Comment by stephenlane** [comment]
@takotakot  i have completely remove ludicrous db and started again and still  not working. When I remove the db config from wp-config then I get the error above.

**Comment by spacedmonkey** [comment]
You get this error when the code can't connect to the database. Can you
check using the MySQL client that the host/user/password work. Do this on
the box itself. When I got this error it was related to security groups in
aws. Hope that helps.

Jonny Harris
http://www.jonathandavidharris.co.uk

On 23 Jun 2017, at 09:07, Stephen Lane <notifications@github.com> wrote:

in log file getting this error.

PHP message: PHP Warning: mysqli_real_connect(): (HY000/2002):
php_network_getaddresses: getaddrinfo failed: Name or service not known in
/var/www/html/mall/wp-includes/wp-db.php on line 1538" while reading
response header from upstream, client: *****, server: _, request: "POST
/mall/wp-admin/admin-ajax.php HTTP/1.1", upstream:
"fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "****", referrer: "
http://********/mall/wp-admin/plugins.php?plugin_status=all&paged=1&s"

Any help much appreciated

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stuttter/ludicrousdb/issues/36#issuecomment-310600984>,
or mute the thread

**Comment by stephenlane** [comment]
@spacedmonkey I have trebled check it, credentials are correct. They match exactly what is in wp-config file.

When i comment out db connection in wp-config these are all the errors I get

`2017/06/23 08:34:21 [error] 9752#9752: *2 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant DB_USER - assumed 'DB_USER' in /var/www/html/mall/wp-includes/load.php on line 404
PHP message: PHP Notice:  Use of undefined constant DB_PASSWORD - assumed 'DB_PASSWORD' in /var/www/html/mall/wp-includes/load.php on line 404
PHP message: PHP Notice:  Use of undefined constant DB_NAME - assumed 'DB_NAME' in /var/www/html/mall/wp-includes/load.php on line 404
PHP message: PHP Notice:  Use of undefined constant DB_HOST - assumed 'DB_HOST' in /var/www/html/mall/wp-includes/load.php on line 404
PHP message: PHP Warning:  mysqli_real_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/mall/wp-includes/wp-db.php on line 1538
PHP message: PHP Warning:  mysqli_real_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/mall/wp-includes/wp-db.php on line 1538" while reading response header from upstream, client: ******, server: _, request: "GET /mall/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "****"
`

**Comment by takotakot** [comment]
@stephenlane 
> When I remove the db config from wp-config
> get the error above
If you get the error soon after you removed the config from wp-config, I think that ludicrousdb is misconfigured. I can only assume you to read https://github.com/stuttter/ludicrousdb again.
I'm sorry if I were wrong.

**Comment by takotakot** [comment]
@stephenlane Set DB_USER and DB_PASSWORD as `""` in wp-config.php.

**Comment by spacedmonkey** [comment]
Can you get WordPress to connect  normally. As in just define user, password and host normally? If Wordpress can't connect normally, then it is your database settings that are wrong

**Comment by stephenlane** [comment]
@spacedmonkey  wordpress connection works perfectly, its just using the plugin is the issue

**Comment by stephenlane** [comment]
@spacedmonkey @takotakot  figure it out. I had the plugin folder name ludicrousdb-master renamed it and now working

**Comment by stephenlane** [comment]
thanks for all yere help

**Comment by JJJ** [comment]
@stephenlane Glad you got it sorted. It’s not ideal to have hard-coded paths in there, but there’s not really a way to know for sure where it would be, at least how it’s coded today.

I’ll think about it more.

**Comment by stephenlane** [comment]
just add to the readme to change the folder name when you download :)
