### ISSUE TITLE
WordPress 4.8 compatibility?

### ISSUE THREAD

**Issue by tonyp-classiccars** [stuttter/ludicrousdb#39]
Any word on compatibility with WP 4.8?

Thanks!

**Comment by spacedmonkey** [comment]
I am currently running it in 4.8 across the board at scale. Maybe we need to change the docs. Have you seen any compabilities issues?

**Comment by tonyp-classiccars** [comment]
Thanks for the response. I haven't testedd it yet because of the compatibility statement in the docs. Glad to hear it runs great on 4.8 at scale. I plan on testing it soon.
