### ISSUE TITLE
Ludicrous' determine_charset shortcircuit because of undefined $dbh.

### ISSUE THREAD

**Issue by krodyrobi** [stuttter/ludicrousdb#40]
The standard `wpdb->determine_charset` method passes over the first if and proceeds to set charset / collation to `utf8mb4 / utf8mb4_unicode_520_ci` for an input of `utf8 / ''`.

This is happening because the default wpdb constructor sets a connection at the end while ludicrous does it after the ini_charset was called (last line in its constructor) somewhere in the query method.

Normally this is not a problem, but for clients not setting the exact precise charset/collation combo in their respective constants will see change in post conditions.

This is obvious if you try to run the Wordpress test suite with ludicrous inside, along with their default config file.

[Ludicrous init_charset called here, dbh undefined at this time](https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L212)

**Comment by JJJ** [comment]
This appears to be a relic from the HyperDB fork. See: https://github.com/Automattic/hyperdb/blob/master/db.php#L185

At a cursory, I'm unsure if we can trust `db_connect()` to handle this now, or if we should consider it a requirement to set precise charset & collations (which is what I've always done myself.)

What happens if you remove the `init_charset()` call from the constructor entirely?

**Comment by krodyrobi** [comment]
It would make sense to only add the charsets after the connection is estableshed with set_charset. But if I remove the ini_charset then it doesn't read from the constants anymore and thus probably the instance variable will be null? (I guess it can be altered after instantiation though so no harm in that)

Also can't see where $charset is set in here https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L753
to warrant that check and use below in `set_charset`, maybe it was just to use the function's default params? (disclaimer: quick glance).

If the charsets are placed in the instance attributes then `parent::db_connect` seems to respect those, and it seems like other places in code including `set_charset` will default to those as well.

I'll have a look into it, but not sure when.

**Comment by JJJ** [comment]
@krodyrobi since you created this issue, the 5.x branch has seen many updates to clean up some of the variable collisions and assignment issues that may have been related to this. Are you able to give the 5.0.0 release a try?

**Comment by JJJ** [comment]
I've confirmed that LudicrousDB is updated & working correctly, relative to the latest WordPress (6.5.x).
