### ISSUE TITLE
work with maria db

### ISSUE THREAD

**Issue by stephenlane** [stuttter/ludicrousdb#41]
hi there,

does this work nicely with maria db?

thanks

**Comment by spacedmonkey** [comment]
On local I use docker and a mariadb container. Works a perfectly.

**Comment by stephenlane** [comment]
hmm, strange. I added this earlier to my installation. All was working nicely, until my connection count on both my read and write database went to 80+ concurrent connections. Removed plugin and dropped down to 9 only.  

This is a dev environment and only 3 users on site
