### ISSUE TITLE
How to be sure that ludicrousdb is even working?

### ISSUE THREAD

**Issue by blur33** [stuttter/ludicrousdb#43]
I've set the parameters, and I'm not seeing any changes on my server logs. I even set intentionally broken perameters and nothing changes.

Edit: I noticed that the files are looking for the  "ludicrousdb" folder but it doesn't say to switch the master folder to "ludicrousdb" and there aren't any error codes for it either.

It's working after switching that.

**Comment by JJJ** [comment]
Thanks for pointing this out. Someone else had a similar issue, and we've updated the readme as a result. Sorry for the confusion!
