### ISSUE TITLE
Is this plugin protected against SQL injection which 4.8.3 fixed? 

### ISSUE THREAD

**Issue by archon810** [stuttter/ludicrousdb#46]
https://blog.ircmaxell.com/2017/10/disclosure-wordpress-wpdb-sql-injection-technical.html instructs us to update both WP and ludicrousdb, but I don't see any recent updates.

**Comment by spacedmonkey** [comment]
This issue effect the prepare method found in core. This drop-in extends wpdb class and doesn't override the prepare method. To protect yourself again this issue, simple upgrade to WP 4.8.3. There is no fault found in ludicrousdb

**Comment by JJJ** [comment]
See a0416caeae84edbd2110ed107267c110092b3bfa.

Both HyperDB and LudicrousDB override the `_real_escape()` method, which does benefit from a fix found in the latest versions of WordPress.

LudicrousDB 4.1.0 is tagged to include this fix. Hat tip to @pento for the nudge.
