### ISSUE TITLE
Does 'timeout' actually work when host is down?

### ISSUE THREAD

**Issue by archon810** [stuttter/ludicrousdb#53]
Hi,

We've used ludicrousdb for years, with 'timeout'  => 0.2 for master and slaves, but whenever the master db goes down and times out (as in, host is down rather than host up and mysql down, which would refuse the connection instantly), the site pretty much goes down because all write and read connections get stuck waiting for the server to come back up rather fail within 0.2s.

Any idea what we're doing wrong?

**Comment by archon810** [comment]
Are timeouts treated differently for reads and writes? I only ever notice these issues when the master db goes down. Slaves can go down and things seem to continue just fine, so I'm wondering if writes disregard the timeout value because they're more important to succeed @JJJ @spacedmonkey?

**Comment by archon810** [comment]
Master db went down again (network keeps failing for some reason on Linode recently every few days), and immediately everything grinds to a halt because timeouts are not properly used.

![image](https://user-images.githubusercontent.com/469543/35476548-af8b04ae-0366-11e8-981a-3f1d5b09e602.png)

**Comment by JJJ** [comment]
Hey @archon810. Sorry; that's really annoying.

There are caveats to how timeouts are handled, but I'll need to look back into the code to refresh my memory of what they are and why they're there.

**Comment by archon810** [comment]
@JJJ Have you had a chance to take a look at this?

**Comment by archon810** [comment]
@spacedmonkey It would be so killer if you could also get this because of the effect it has on production when a db host goes down. Thank you!!

**Comment by archon810** [comment]
cc @sebsz

**Comment by JJJ** [comment]
Some changes just got pushed to master that should resolve this, specifically around timeouts and TCP timeouts.

The only other thing I can think of that _might_ be an issue, is the extra caching that was added needs to be reverted. It's nice to have, but does introduce some complexity, and it turns a simple loop into something that requires access to an external cache. We'll see?

**Comment by archon810** [comment]
@JJJ Any idea on the timing of the release?
