### ISSUE TITLE
WordPress database error Unknown column 'Tables_in_' ..

### ISSUE THREAD

**Issue by stevenmunro** [stuttter/ludicrousdb#54]
I have a database server specified in wp-config.php, and I've added that in db-config.php along with another master replica.

If I disable ludicrousdb, this particular plugin (WP Statistics) works normally. If I enable ludicrousdb the plugin complains that certain DB table don't exist (they clearly do).

This is the error being generated in wp_debug.log

> WordPress database error Unknown column 'Tables_in_' in 'where clause' for query SHOW TABLES WHERE `Tables_in_` = 'wp_statistics_visitor' OR `Tables_in_` = 'wp_statistics_visit' OR `Tables_in_` = 'wp_statistics_exclusions' OR `Tables_in_` = 'wp_statistics_historical' OR `Tables_in_` = 'wp_statistics_pages' OR `Tables_in_` = 'wp_statistics_useronline' OR `Tables_in_` = 'wp_statistics_search' made by do_action('toplevel_page_wps_overview_page'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Statistics_Admin_Pages::log, wpdb->print_error

I'm not sure why?

**Comment by stevenmunro** [comment]
This is happening because inside the statistics plugin, $wpdb->dbname returns NULL.

**Comment by JJJ** [comment]
LudicrousDB requires you to define your database tables in a callback configuration. My guess is that these tables aren't defined, or don't exist in the database and/or server that is defined.
