### ISSUE TITLE
Major bug in LudicrousDB server connection retry logic?

### ISSUE THREAD

**Issue by SeBsZ** [stuttter/ludicrousdb#57]
In class-ludicrousdb.php in function check_connection() lines 1115-1132 there is code to retry making a database connection several times. On line 1123 there is the code that actually retries making a connection:

```
if ( $this->db_connect( false ) ) {
  if ( $error_reporting ) {
    error_reporting( $error_reporting );
  }

  return true;
}
```

However, looking at the first few lines of the function db_connect, it is clear that this thing is always going to return false and a connection will never be retried:

```
public function db_connect( $query = '' ) {
  // Bail if empty query
  if ( empty( $query ) ) {
    return false;
  }
  ...
```

The confusion probably stems from the fact that the original db_connect function from wp-db.php is defined as follows:
`public function db_connect( $allow_bail = true ) {`
This function does allow 'false' to be passed in. In fact, it looks like most of the check_connection() function was copied from wp-db.php, but not modified to work with LudicrousDB's db_connect() function.

I stepped through the code and see it not working correctly, I'm just wondering if I overlooked something? Please let me know if I can help out in any way.

**Comment by archon810** [comment]
@JJJ I know you're not very active in this project these days, but if you could find some time to take a look at the recent issues, and this one especially, it'd be amazing.

**Comment by kkmuffme** [comment]
Actually since check_connection is only called once (as part of function db_connect):

`if ( ! $this->check_connection( false, $this->dbhs[ $dbhname ] ) ) {`

and having false parameter here, the code you mention can never be reached, since line 1103-1105 directly above the code you mentioned will always return false then:

```
if ( false === $allow_bail ) {
	return false;
}
```

So all code after it can be removed basically, unless someone has a use case for manually calling the check_connection function which afaik there is none.

**Comment by SeBsZ** [comment]
@kkmuffme you realize you are repeating exactly what I said? The line numbers have changed a little, but we're both saying the same thing. The retrying of establishing a database connection in LudicrousDB is broken because db_connect is passed false in check_connection. This makes the whole db_connect function bail immediately. This bug needs attention, as it is major in my opinion.

And yes, we do call check_connection manually. Why would you think no one has a use case for calling check_connection? It's an integral part of checking whether the database connection is still active for example in a long running script.

Here's the check_connection function comment in class-ludicrousdb.php:

> Check that the connection to the database is still up. If not, try to reconnect

Well this statement is false. It will not, ever, try to reconnect on its own.

**Comment by kkmuffme** [comment]
Yes exactly, I just wanted to point attention to this issue once more bc I also think its a major bug.

"check_connection manually" - waste of time in my opinion.
MySQL will not terminate a connection within reasonable time (actually multiple hours unless set different in my.cnf), so usually by that time your php has timed out long ago already (and if you do really have scripts that run that long, I suggest you fix your code and utilize an async queue by splitting your big task in multiple sub tasks)
If mysql connection fails (e.g. bc mysql read slave is down) then we do want to reconnect - but that should happen automatically & also to a different slave so we don't waste time connecting to a server that might be down as our previous connection was terminated.

>> Check that the connection to the database is still up. If not, try to reconnect
> Well this statement is false. It will not, ever, try to reconnect on its own.

Yes, I totally agree we should fix the implementation for this. When changing this, we could also implement https://github.com/stuttter/ludicrousdb/issues/63 to avoid mysqli_ping slowing down the site bc it checks on each & every sql request

**Comment by JJJ** [comment]
For context, IIRC, the reason this gets missed is because it’s one of the few remaining usages of `explode()` that didn’t get cleaned up.

I am totally in favor of fixing this, preferably in a way that also cleans up the `explode()` but that’s secondary.

**Comment by spacedmonkey** [comment]
Thanks @SeBsZ @kkmuffme for your feedback on this. I am Jonny, the other maintainer of this plugin.

To give you some context on this, I added the `check_connection` method. This is a port of the same method found in core. The reason it was ported, was to make sure compatibility. The code to retry content is never meant to be called. 

I do understand it is a little confusing, but it feels like this code should do something. It isn't matter of turning this functionality on. Turning this on changes the functionality of the drop-in and may mean more stills displaying the wp_die message, which something not every install will want. I think we should add an ever param into the config, so we can turn this functionality on and off.

**Comment by kkmuffme** [comment]
@spacedmonkey good idea, just one thing I am not sure about: mysqli_ping before depended on the result of get_db_object (so basically the thread id of mysql connection which is used for a specific table) but now you are checking a db server that might not even get called bc things are overwritten in get_db_object ?

Also I don't understand the 0.1 - bc if it goes away, we will get the error anyway and if its still there why should we ping it again after 0.1s?
We basically just need to check if we get an error that we connect to another server and remove the failed server from the pool (so we don't end up trying to connect to it again)

**Comment by spacedmonkey** [comment]
Fixed in https://github.com/stuttter/ludicrousdb/pull/64 and part of 4.2 release.
