### ISSUE TITLE
Query overide apply_filters_ref_array cannot work

### ISSUE THREAD

**Issue by sirshurf** [stuttter/ludicrousdb#58]
We have this great query override:

apply_filters_ref_array

BUT, the code is set to return the data from the override:

			$return_val = apply_filters_ref_array( 'pre_query', array( null, $query, &$this ) );
			if ( null !== $return_val ) {
				return $return_val;
			}

BUT if we will look at wp-db->query()
		if ( $query ) {
			$this->query( $query );
		} else {
			return null;
		}

The data from the query is NOT set to the data properties

We need to change it to be
			$return_val = apply_filters_ref_array( 'pre_query', array( null, $query, &$this ) );
			if ( null !== $return_val ) {
				return $this->last_result=$return_val;
			}

**Comment by spacedmonkey** [comment]
Thanks for your feedback @sirshurf 

The filter is functionality correctly. Not every path of the code sets `$this->last_result` as well. Take for example [this](https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L1321-L1341), there are two if statements that don't set it. For example an update or insert query wouldn't get results. Lucky enough, I already thought of this. 

The filter passes, by reference, the whole current object. So you can do something like this 
```
add_filter('pre_query', function($return_val, $query, $db_class){
     if ( preg_match( "/^\\s*(insert|delete|update|replace|alter) /i", $query ) ) {
         return $db_class->last_result=$return_val;
      }
      return $return_val
}, 10, 3);
```

As you can see, you really have power with this filter to do whatever you want. 
I hope this answers your point. I am closing this ticket out. Free feel to reopen if I have missed something.
