### ISSUE TITLE
mysqli_ping waste of time

### ISSUE THREAD

**Issue by kkmuffme** [stuttter/ludicrousdb#63]
ludicrousdb runs check_connection for each & every query, triggering a mysqli_ping. This is a complete waste of resources & slows down things unnecessarily.

Suggestion to change:
Scenario 1: default - fastest
run the connection check once and if connection is up, wp_cache_set the $dbh->thread_id in check_connection as a temporary/non-permanent group, so we will not mysqli_ping within this page load for the same connection.

Scenario 2: no writes must get lost - slower (depends on number of writes & caching of reads in object cache, but more secure); e.g. via constant
same as 1, except we check that if $operation === write we will still mysqli_ping to make sure no writes get lost even when the db server crashes while the page loads
this also only makes sense if you have a master-master setup where another master can accept the writes if one master goes down.

Scenario 3: no writes/reads must get lost - we always want to failover/check if connection is still up - slowest
this is what is currently implemented.

Note: by default object cache is only non-persistent, so the group we use won't matter.
For people using object caches however, they would need to add our group to the ignored groups.
Thus, if we don't want this, alternatively, we could just create a global variable and add the thread_ids to it (& check it) instead of using wp_cache

**Comment by JJJ** [comment]
Good catch.

What if we bottled your 3 logic scenarios up into a private method to determine the best approach?

It would be a nice touch if we intelligently checked for a cached value, detected a master-master setup, then fell-back to what’s here now.

It’s fine to introduce caching to this IMO. We should be able to add our own group to the non-persistent array (I believe we do that already.)

We could also add a thread_ids array to the wpdb global. It depends on if we think there’s value in storing it remotely, like if we want to reconnect to a thread from a second request or something?

**Comment by kkmuffme** [comment]
I just double checked based on your suggestion, and you are correct, most object caches have a add_non_persistent_groups( $groups ) function, where we could add our own non-persistent group.

not even sure we really need all 3 scenarios - afaik the first/1) should suffice as this is how it works in default WP too, so not really sure if we should extend these high maintenance but low use cases.

> We could also add a thread_ids array to the wpdb global. It depends on if we think there’s value in storing it remotely, like if we want to reconnect to a thread from a second request or something?

Do you think this will have any performance gains?
I think hardly anyone will use this, so it would just increase wpdb global size.

**Comment by spacedmonkey** [comment]
Hi all. I worked on a solution for this issue, as I agree, checking every call is a little wasteful. 
@kkmuffme can you take a look at https://github.com/stuttter/ludicrousdb/pull/66 and see what you think.

**Comment by JJJ** [comment]
#66 was merged to master.

Let's run with it and see how it goes? Can reopen this if it's worse?

**Comment by kkmuffme** [comment]
Sorry, I totally forgot to create a pull request for this, since I created my own solution quite quickly back then. (now just remembered bc got some PHP7.3 notices, so I checked back to the plugin and realised it)

I checked your solution and it doesn't really solve the issue, bc:
MySQL server rarely goes away, so pinging them more than once per page load is a waste of resources.
The worst that can happen is that user has to reload the page, if the server goes away while he loads the page. (since on the next page load the server is gone, it will not reselect that server anyway)
This will a few a handful (literally) of users per year when you have millions of uncached (!) pageviews, so adding a heartbeat/continous ping just hogs ressources & slows down the experience for 99.9% of other users.

The only real drawback is, that if the server goes away while a long running script is ongoing, this script will not be able to finish (& has to restart). This however is in line with what happens if you are using default WP.

I created a pull request with my current solution https://github.com/stuttter/ludicrousdb/pull/79
Please let me know what you think and if I should change anything.
