### ISSUE TITLE
Improve drop-in experience

### ISSUE THREAD

**Issue by johnjamesjacoby** [stuttter/ludicrousdb#7]
In WP Spider Cache, I went the route of including the actual drop-in files in a `drop-ins` directory.

This made it easier for developers of the plugin to separate out classes, functions, and configurations, and also made it a bit more obvious which files are WordPress drop-ins.

It also would allow for Ludicrous DB to live in its own directory, and for the drop-ins to be `require`d instead. I think this is cleaner, but would like to get some feedback before making these changes.

Thoughts?

**Comment by spacedmonkey** [comment]
I have been looking into this for installing the files using composer. 

https://github.com/Koodimonni/Composer-Dropin-Installer

**Comment by johnjamesjacoby** [comment]
I'm going to work on this tomorrow using a similar approach to what's in WP Spider Cache.

**Comment by johnjamesjacoby** [comment]
Done.

Shouldn't break anything for existing installations, but because of the drop-in nature of LudicrousDB, and everyone being forced to roll-their-own configurations, it's plausible people have hacks in place to shim their own installs.

Anyone running into this, please create new issues for related problems. Thanks!
