### ISSUE TITLE
Need help with Partitioning config

### ISSUE THREAD

**Issue by quangbahoa** [stuttter/ludicrousdb#71]
Hi there,

I'm try to setup db partitioning for multisite with 15 child sites. Currently I'm config as `Sample Configuration 2: Partitioning` and it work. All child site tables are stored on `blogdb`. Now I want config 5 child sites on a db. Eg,
 - Site id 2-5 stored on db name call `child_db_2_5`
 - Site id 6-10 stored on db name call `child_db_6_10`
 - Site id 11-15 stored on db name call `child_db_11_15`

How can I do that?

Thanks for your help,
Regards,

**Comment by deepak166** [comment]
even i would like to know if there is a solution

**Comment by JJJ** [comment]
Moved to: https://github.com/stuttter/ludicrousdb/discussions/157
