### ISSUE TITLE
PHP7.3 notice compact(): Undefined variable: queries Undefined variable: lag

### ISSUE THREAD

**Issue by kkmuffme** [stuttter/ludicrousdb#77]
Coming from this line: $this->last_connection    = compact( 'dbhname', 'host', 'port', 'user', 'name', 'tcp', 'elapsed', 'success', 'queries', 'lag' );

**Comment by takotakot** [comment]
@kkmuffme See #74 (merged). Try this [change](https://github.com/stuttter/ludicrousdb/pull/74/files) and close this issue.
If your problem remains, comment here again.
