### ISSUE TITLE
table name empty when COMMIT

### ISSUE THREAD

**Issue by kkmuffme** [stuttter/ludicrousdb#82]
There is a bug, when the query is just a "COMMIT" of a transaction.

The issue came up by the error "Deprecated: stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /ludicrousdb/includes/class-ludicrousdb.php" which was reported in https://github.com/stuttter/ludicrousdb/issues/72 (& not fixed yet)

$this->last_table = $this->table = $this->get_table_from_query( $query );

will be false.
This will then lead to all kinds of issues further below, one of which is that notice mentioned above.
We could change the false to '', but I think setting it to 'no-table' makes it clearer for later debugging purposes.

Pull request created: https://github.com/stuttter/ludicrousdb/pull/81

**Comment by JJJ** [comment]
#81 merged to master.
