### ISSUE TITLE
W3 Total Cache and ludicrousdb plugin conflict 

### ISSUE THREAD

**Issue by wobeng** [stuttter/ludicrousdb#83]
W3 Total Cache is conflicting with ludicrousdb plugin as they both put "db.php" file in "wp-content" directory.

Can we fix that conflict please ?

**Comment by takotakot** [comment]
If you want to use ludicrousdb, put ludicrousdb version's `db.php`.

**Comment by wobeng** [comment]
Hi @takotakot but I also want to use W3 Total Cache database caching also. When I add the db.php I get an error in wordpress

The Database add-in file db.php is not a W3 Total Cache drop-in. Remove it or disable Database Caching.

**Comment by takotakot** [comment]
Hi @wobeng, there are many types of Cache plugins. Maybe it's difficult to merge code or avoid conflicts.

For an easy case, rename `db.php` to `db-cache.php` and rewrite some code may work.
ref: https://dev.classmethod.jp/etc/wordpress-hyperdb-w3-total-cache/
(Soffy for Japanese content.)

**Comment by wobeng** [comment]
@takotakot thanks for that ref, question how come ludicrousdb don't adjust db instead of adjusting w3-total-cache

**Comment by takotakot** [comment]
I think put `db-ludicrous.php` (from ludicrousdb) and modify `db.php` (of w3tc) to include `db-ludicrous.php` MAY work (not tested).

**Comment by wobeng** [comment]
what happens if w3tc get updated?

**Comment by takotakot** [comment]
Think and try!

**Comment by wobeng** [comment]
I have it working :), im just trying to think of a way to help someone in the future that want to install both without any conflict :)

**Comment by JJJ** [comment]
Because of the way that WordPress Drop-in plugins work, only one can be easily dropped in place at a time. Trying to use both is risky, and not really a directly supported feature, but I'm happy to fix any bugs that happen from the result of advanced setups like this, simply because I think they're neat. 🤗

**Comment by archon810** [comment]
I'd love to see W3TC working with ludicrousdb, been wondering if it's possible myself. Perhaps the two projects could collaborate to make that happen?

**Comment by sous-studio** [comment]
> I have it working :), im just trying to think of a way to help someone in the future that want to install both without any conflict :)

Hi! Care to share for recipe? Like you include require_once "{$wp_plugin_dir}/{$ldb_dirname}/ludicrousdb.php" inside W3tc' db.php? Before or after W3tc's code? Any side effects?
