### ISSUE TITLE
ludicrousdb still work with latest 5.2.2?

### ISSUE THREAD

**Issue by wobeng** [stuttter/ludicrousdb#84]
1. Copy the main directory `ludicrousdb`  into plugin folder wp-content/plugins/ludicrousdb/
2. I copied the drop ins
```
db.php <-> wp-content/db.php - Bootstrap for replacement $wpdb object
db-error.php <-> wp-content/db-error.php - Endpoint for fatal database error output to users
db-config.php <-> ABSPATH/db-config.php - For configuring your database environment
```
3. I configured db-config.php  with write and read database, and nothing has happened. 

Am I missing anything?

**Comment by takotakot** [comment]
Write PHP, MySQL (or MariaDB) versions may help more.

(Be sure `db-config.php` is in the same directory having `wp-config.php`)
