### ISSUE TITLE
Using $table instead of $this->table always results in using master

### ISSUE THREAD

**Issue by sirilyan** [stuttter/ludicrousdb#85]
https://github.com/stuttter/ludicrousdb/blob/b915af6d289d9e2551889ffefa95b63e534cdb83/ludicrousdb/includes/class-ludicrousdb.php#L433

There's no variable `$table` in this function, so this always sets `$this->table` to "no-table". Reads never go to a secondary since the plugin thinks they have some sort of dependency on master.

Changing to `$this->table` seems to do the right thing. If you'd like, I can cut a PR for it.

**Comment by musthavetickets** [comment]
I have found the issue as well that it never uses the read server.. I have the  master as write = 1 and read = 0, and the read server as write = 0 and read = 1. But the reads still goto the master. If I swap the write from the master to the slave, then the read also comes to the slave. I have updated line 433 with the above and it now works. Thanks.

**Comment by sirilyan** [comment]
PR cut.

**Comment by JJJ** [comment]
Merged. Thank you both!
