### ISSUE TITLE
Installation: Files vs Drop-ins OR Files and Drop-ins

### ISSUE THREAD

**Issue by wobeng** [stuttter/ludicrousdb#90]
When installing can I pick to install it using Files or Drop-ins or I have to do both?

**Comment by lsemenenko** [comment]
From my experience you can just use drop-ins. But, I agree it's confusing.

**Comment by wobeng** [comment]
so you have to do both?

**Comment by lsemenenko** [comment]
I believe you need to have the drop-ins in place, and the plugin needs to be extracted to the plugins folder. That's how I do it anyway. If you check in the code (I'm lazy sorry) I believe it doesn't work unless the plugin folder explicitly exists.

**Comment by takotakot** [comment]
`mu-plugins` is the directory for "must use" plugins.
