### ISSUE TITLE
Cron race conditions

### ISSUE THREAD

**Issue by kkmuffme** [stuttter/ludicrousdb#92]
This is not ludicrousdb specific (as these cron race conditions can also happen with default WP) but ludicrousdb increases the likelihood of it happening:

since all crons are stored in 1 option in master, it can easily happen that crons are executed twice or crons not added, if WP reads this option from slave & updates it on master, while slave had stale data because another request updated cron on master in the meantime.

when wp_schedule_event (or single event) is called, you need to first read the current cron value from db master BEFORE you make any changes to it & write it back.

Not sure how relevant this fix is though, as usually if you encounter this, it's time to move to a proper cron handler like Cavalcade or similar.

Note: I'm not interested in a fix, since we use a custom cron handler like Cavalcade (like wordpress.com does), but I wanted to let you know about it as you might want to fix this for yourself & other users.

**Comment by spacedmonkey** [comment]
This is an upstream issue that is found in core. More details in the [ticket](https://core.trac.wordpress.org/ticket/31245). Today the patch was merged. So this issue so now be resolved.
