### ISSUE TITLE
Errors not detected properly if SQL_CALC_FOUND_ROWS is set

### ISSUE THREAD

**Issue by rmccue** [stuttter/ludicrousdb#93]
Due to the way that the `SQL_CALC_FOUND_ROWS` support works, errors aren't detected correctly, so `last_error` is not set properly.

When you make a query with `SQL_CALC_FOUND_ROWS`, Ludicrous immediately runs `SELECT FOUND_ROWS()` for you. This resets the MySQL error state, so when Ludicrous calls `mysqli_error( $this->dbh )`, it's now set to the error state for the `SELECT FOUND_ROWS()` query.

**Comment by takotakot** [comment]
@rmccue https://github.com/stuttter/ludicrousdb/blob/253dba7c81265ef875b9e772a65a93a50149c67d/ludicrousdb/includes/class-ludicrousdb.php#L27-L31
does this comment help you?

**Comment by rmccue** [comment]
@takotakot Yep, I know how it works internally. :)

The problem is that `$this->_do_query()` is called twice, where the first one is the query itself and the latter is the FOUND_ROWS() query. `mysqli_error()` is only called after the latter query, so misses the error from the actual query itself.

I’ll send a PR shortly.

**Comment by takotakot** [comment]
@rmccue OK. I get that the code have to be modified. ( I thought that 1. adding `NO_SELECT_FOUND_ROWS`, 2. manually get error, and 3. call `SELECT FOUND_ROWS();` can satisfy your demand. )

**Comment by rmccue** [comment]
I want the behaviour that’s in there, we just need to fix it :)

**Comment by spacedmonkey** [comment]
@rmccue  Have you had any luck working out a fix for this?

**Comment by rmccue** [comment]
It looks like these may have actually been fixed in 1256f00c082ca683a202fdb4867235c335f3ba69 but need backporting to the 4.x branch.

**Comment by JJJ** [comment]
After a private consult with @rmccue, since this is resolved in 5.x, I'm going to mark this as closed.
